Repository run-llama/llama_deploy, pull requests merged in 2024-11, with the labels that each got.

#372 Use the new SDK within the api server
  llama_deploy/apiserver/deployment.py
  llama_deploy/apiserver/routers/deployments.py
  llama_deploy/apiserver/routers/status.py
  llama_deploy/client/models/apiserver.py
  llama_deploy/types/__init__.py
  llama_deploy/types/apiserver.py
  tests/apiserver/routers/test_deployments.py
  tests/apiserver/routers/test_status.py
  tests/client/models/test_apiserver.py
Labels: enhancement

#345 Integrate the Solace PubSub+ broker into LlamaDeploy
  examples/message-queue-integrations/README.md
  examples/message-queue-integrations/_app/multi_workflows_app/deployment/core.py
  examples/message-queue-integrations/_app/pyproject.toml
  examples/message-queue-integrations/solace/docker/.env.solace
  examples/message-queue-integrations/solace/docker/docker-compose.yml
  examples/message-queue-integrations/solace/quick_start/.env.solace
  examples/message-queue-integrations/solace/quick_start/README.md
  examples/message-queue-integrations/solace/quick_start/deploy_core.py
  examples/message-queue-integrations/solace/quick_start/deploy_workflow.py
  examples/message-queue-integrations/solace/quick_start/interaction_concurrent.py
  examples/message-queue-integrations/solace/quick_start/interaction_multi_flows.py
  examples/message-queue-integrations/solace/quick_start/interaction_simple.py
  llama_deploy/apiserver/config_parser.py
  llama_deploy/apiserver/deployment.py
  llama_deploy/deploy/deploy.py
  llama_deploy/message_queues/__init__.py
  llama_deploy/message_queues/solace.py
  poetry.lock
  pyproject.toml
  tests/message_queues/test_solace.py
Labels: enhancement, integration

#386 fix: fix rabbitmq import errors
  e2e_tests/message_queues/message_queue_rabbitmq/__init__.py
  e2e_tests/message_queues/message_queue_rabbitmq/conftest.py
  e2e_tests/message_queues/message_queue_rabbitmq/docker-compose.yml
  e2e_tests/message_queues/message_queue_rabbitmq/test_message_queue.py
  e2e_tests/message_queues/message_queue_rabbitmq/workflow.py
  llama_deploy/apiserver/deployment.py
  llama_deploy/deploy/deploy.py
  llama_deploy/message_queues/rabbitmq.py
  tests/apiserver/test_deployment.py
  tests/message_queues/test_rabbitmq.py
Labels: bug
